sudo: false

notifications:
  email: false
os:
 - windows
 - linux
 - osx

dist: xenial

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

install:
  - pip install -U pip
  - pip install codecov
  - pip install -r requirements.txt

script:
 - coverage run oneforall/example.py

after_success:
 - codecov